### ISSUE TITLE
Umbrella issue for code lint

### ISSUE THREAD

**Issue by calvin0327** [karmada-io/karmada-operator#7]
Here is a list of TODOs that help us to verify code specification, we should support following basic actions: 
- [ ]  verify files generated by `code-generator` are consistent
- [ ]  verify crd yaml files genetated by `controller-gen` are consistent
- [ ]  verify vendor dir genetated by command `go mod vendor` are consistent
- [ ]  import aliases verification
- [ ]  code static check

Except above ci actions, we alse need  commands of `Makefile` to exec in the process of develpment:
- [ ]  generated and verify files generated by `code-generator`
- [ ]  generated and verify crd yaml files genetated by `controller-gen`
- [ ]  generated and verify vendor dir
- [ ]  update and verify import aliases
- [ ]  code static check
